language: ruby
sudo: false
before_install:
  - gem install bundler
  - curl -sL https://static.rust-lang.org/rustup.sh -o ~/rust-installer/rustup.sh
  - sh ~/rust-installer/rustup.sh --prefix=~/rust --spec=nightly -y --disable-sudo 2> /dev/null
  - rustc --version
  - cargo --version
before_script:
  - bundle install
rvm:
  - 2.3.0
notifications:
  email: false