language: ruby
sudo: false
before_install:
  - gem install bundler
before_script:
  - bundle install
rvm:
  - 2.6.5
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "irc.esper.net#SatanicSanta"
