language: ruby
sudo: false
before_install:
  - gem install bundler
  - curl -sL https://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz | tar --strip-components=1 -C ~/rust -xzf -
  - curl -sL https://static.rust-lang.org/cargo-dist/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz | tar --strip-components=1 -C ~/rust -xzf -
  - rustc --version
  - cargo --version
before_script:
  - bundle install
rvm:
  - 2.3.0
notifications:
  email: false